language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
install:
  - python setup.py install
  - pip install coverage
script: coverage run setup.py test
after_success:
  - pip install coveralls
  - coveralls
